# Generated by Django 5.0.6 on 2024-07-12 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.collectiontitles'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.test'),
        ),
        migrations.AddField(
            model_name='answerset',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.test'),
        ),
    ]
