# Generated by Django 5.0.6 on 2024-07-12 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_initial'),
        ('collection', '0003_alter_titleentry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='collection.collectiontitles'),
        ),
    ]
