# Generated by Django 5.0.6 on 2024-07-12 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_prepopulate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titleentry',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='collection.collectiontitles'),
        ),
    ]
